// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://krmgmrkrdyfhryrhfycs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtybWdtcmtyZHlmaHJ5cmhmeWNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwMDAzODksImV4cCI6MjA3MDU3NjM4OX0.6TbGzlipEJTeEfnpevxmUj6n-Tol5OpYAw4IBaytI50";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});