// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://axzidpfcdvfpizeiosxh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF4emlkcGZjZHZmcGl6ZWlvc3hoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyOTkxNDIsImV4cCI6MjA2OTg3NTE0Mn0.GM-pHZDIN_WsWvRfyJQOqLxdpPMekvtjNkbHpsLVgvg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});